export const SI_DO_CODE_AND_NAME = [
  { name: '서울특별시', code: '11' },
  { name: '부산광역시', code: '21' },
  { name: '대구광역시', code: '22' },
  { name: '인천광역시', code: '23' },
  { name: '광주광역시', code: '24' },
  { name: '대전광역시', code: '25' },
  { name: '울산광역시', code: '26' },
  { name: '세종특별자치시', code: '29' },
  { name: '경기도', code: '31' },
  { name: '강원특별자치도', code: '32' },
  { name: '충청북도', code: '33' },
  { name: '충청남도', code: '34' },
  { name: '전북특별자치도', code: '35' },
  { name: '전라남도', code: '36' },
  { name: '경상북도', code: '37' },
  { name: '경상남도', code: '38' },
  { name: '제주특별자치도', code: '39' },
];
export const DISTRICTS_CODE_AND_NAME = {
  서울특별시: [
    {
      name: '종로구',
      code: '11010',
      adjacency: [
        { name: '은평구', code: '11120' },
        { name: '서대문구', code: '11130' },
        { name: '중구', code: '11020' },
        { name: '성북구', code: '11080' },
        { name: '동대문구', code: '11060' },
      ],
    },
    {
      name: '중구',
      code: '11020',
      adjacency: [
        { name: '종로구', code: '11010' },
        { name: '서대문구', code: '11130' },
        { name: '용산구', code: '11030' },
        { name: '성동구', code: '11040' },
        { name: '동대문구', code: '11060' },
      ],
    },
    {
      name: '용산구',
      code: '11030',
      adjacency: [
        { name: '중구', code: '11020' },
        { name: '성동구', code: '11040' },
        { name: '서초구', code: '11220' },
        { name: '동작구', code: '11200' },
        { name: '마포구', code: '11140' },
        { name: '영등포구', code: '11190' },
      ],
    },
    {
      name: '성동구',
      code: '11040',
      adjacency: [
        { name: '중구', code: '11020' },
        { name: '동대문구', code: '11060' },
        { name: '광진구', code: '11050' },
        { name: '강남구', code: '11230' },
        { name: '용산구', code: '11030' },
      ],
    },
    {
      name: '광진구',
      code: '11050',
      adjacency: [
        { name: '성동구', code: '11040' },
        { name: '동대문구', code: '11060' },
        { name: '중랑구', code: '11070' },
        { name: '강동구', code: '11250' },
        { name: '송파구', code: '11240' },
      ],
    },
    {
      name: '동대문구',
      code: '11060',
      adjacency: [
        { name: '성북구', code: '11080' },
        { name: '종로구', code: '11010' },
        { name: '중구', code: '11020' },
        { name: '성동구', code: '11040' },
        { name: '광진구', code: '11050' },
        { name: '중랑구', code: '11070' },
      ],
    },
    {
      name: '중랑구',
      code: '11070',
      adjacency: [
        { name: '노원구', code: '11110' },
        { name: '광진구', code: '11050' },
        { name: '동대문구', code: '11060' },
        { name: '성북구', code: '11080' },
      ],
    },
    {
      name: '성북구',
      code: '11080',
      adjacency: [
        { name: '종로구', code: '11010' },
        { name: '동대문구', code: '11060' },
        { name: '강북구', code: '11090' },
        { name: '노원구', code: '11110' },
        { name: '중랑구', code: '11070' },
      ],
    },
    {
      name: '강북구',
      code: '11090',
      adjacency: [
        { name: '도봉구', code: '11100' },
        { name: '성북구', code: '11080' },
        { name: '노원구', code: '11110' },
      ],
    },
    {
      name: '도봉구',
      code: '11100',
      adjacency: [
        { name: '강북구', code: '11090' },
        { name: '노원구', code: '11110' },
      ],
    },
    {
      name: '노원구',
      code: '11110',
      adjacency: [
        { name: '도봉구', code: '11100' },
        { name: '강북구', code: '11090' },
        { name: '성북구', code: '11080' },
        { name: '중랑구', code: '11070' },
      ],
    },
    {
      name: '은평구',
      code: '11120',
      adjacency: [
        { name: '서대문구', code: '11130' },
        { name: '종로구', code: '11010' },
        { name: '마포구', code: '11140' },
      ],
    },
    {
      name: '서대문구',
      code: '11130',
      adjacency: [
        { name: '은평구', code: '11120' },
        { name: '종로구', code: '11010' },
        { name: '중구', code: '11020' },
        { name: '마포구', code: '11140' },
      ],
    },
    {
      name: '마포구',
      code: '11140',
      adjacency: [
        { name: '은평구', code: '11120' },
        { name: '서대문구', code: '11130' },
        { name: '용산구', code: '11030' },
        { name: '영등포구', code: '11190' },
        { name: '강서구', code: '11160' },
      ],
    },
    {
      name: '양천구',
      code: '11150',
      adjacency: [
        { name: '강서구', code: '11160' },
        { name: '구로구', code: '11170' },
        { name: '영등포구', code: '11190' },
      ],
    },
    {
      name: '강서구',
      code: '11160',
      adjacency: [
        { name: '양천구', code: '11150' },
        { name: '영등포구', code: '11190' },
        { name: '마포구', code: '11140' },
      ],
    },
    {
      name: '구로구',
      code: '11170',
      adjacency: [
        { name: '영등포구', code: '11190' },
        { name: '양천구', code: '11150' },
        { name: '금천구', code: '11180' },
        { name: '관악구', code: '11210' },
      ],
    },
    {
      name: '금천구',
      code: '11180',
      adjacency: [
        { name: '구로구', code: '11170' },
        { name: '관악구', code: '11210' },
      ],
    },
    {
      name: '영등포구',
      code: '11190',
      adjacency: [
        { name: '양천구', code: '11150' },
        { name: '구로구', code: '11170' },
        { name: '동작구', code: '11200' },
        { name: '마포구', code: '11140' },
        { name: '용산구', code: '11030' },
        { name: '강서구', code: '11160' },
      ],
    },
    {
      name: '동작구',
      code: '11200',
      adjacency: [
        { name: '용산구', code: '11030' },
        { name: '서초구', code: '11220' },
        { name: '관악구', code: '11210' },
        { name: '영등포구', code: '11190' },
      ],
    },
    {
      name: '관악구',
      code: '11210',
      adjacency: [
        { name: '동작구', code: '11200' },
        { name: '서초구', code: '11220' },
        { name: '구로구', code: '11170' },
        { name: '금천구', code: '11180' },
      ],
    },
    {
      name: '서초구',
      code: '11220',
      adjacency: [
        { name: '용산구', code: '11030' },
        { name: '동작구', code: '11200' },
        { name: '관악구', code: '11210' },
        { name: '강남구', code: '11230' },
      ],
    },
    {
      name: '강남구',
      code: '11230',
      adjacency: [
        { name: '서초구', code: '11220' },
        { name: '송파구', code: '11240' },
        { name: '성동구', code: '11040' },
      ],
    },
    {
      name: '송파구',
      code: '11240',
      adjacency: [
        { name: '강남구', code: '11230' },
        { name: '강동구', code: '11250' },
        { name: '광진구', code: '11050' },
      ],
    },
    {
      name: '강동구',
      code: '11250',
      adjacency: [
        { name: '송파구', code: '11240' },
        { name: '광진구', code: '11050' },
      ],
    },
  ],
  부산광역시: [
    {
      name: '중구',
      code: '21010',
      adjacency: [
        { name: '서구', code: '21020' },
        { name: '동구', code: '21030' },
        { name: '영도구', code: '21040' },
      ],
    },
    {
      name: '서구',
      code: '21020',
      adjacency: [
        { name: '중구', code: '21010' },
        { name: '사하구', code: '21100' },
        { name: '부산진구', code: '21050' },
        { name: '동구', code: '21030' },
      ],
    },
    {
      name: '동구',
      code: '21030',
      adjacency: [
        { name: '중구', code: '21010' },
        { name: '서구', code: '21020' },
        { name: '부산진구', code: '21050' },
        { name: '남구', code: '21070' },
        { name: '영도구', code: '21040' },
      ],
    },
    {
      name: '영도구',
      code: '21040',
      adjacency: [
        { name: '중구', code: '21010' },
        { name: '동구', code: '21030' },
        { name: '남구', code: '21070' },
        { name: '서구', code: '21020' },
      ],
    },
    {
      name: '부산진구',
      code: '21050',
      adjacency: [
        { name: '서구', code: '21020' },
        { name: '동구', code: '21030' },
        { name: '남구', code: '21070' },
        { name: '연제구', code: '21130' },
        { name: '동래구', code: '21060' },
        { name: '금정구', code: '21110' },
        { name: '북구', code: '21080' },
        { name: '사상구', code: '21150' },
      ],
    },
    {
      name: '동래구',
      code: '21060',
      adjacency: [
        { name: '부산진구', code: '21050' },
        { name: '연제구', code: '21130' },
        { name: '금정구', code: '21110' },
        { name: '해운대구', code: '21090' },
        { name: '북구', code: '21080' },
      ],
    },
    {
      name: '남구',
      code: '21070',
      adjacency: [
        { name: '동구', code: '21030' },
        { name: '부산진구', code: '21050' },
        { name: '수영구', code: '21140' },
        { name: '영도구', code: '21040' },
      ],
    },
    {
      name: '북구',
      code: '21080',
      adjacency: [
        { name: '부산진구', code: '21050' },
        { name: '동래구', code: '21060' },
        { name: '금정구', code: '21110' },
        { name: '강서구', code: '21120' },
        { name: '사상구', code: '21150' },
      ],
    },
    {
      name: '해운대구',
      code: '21090',
      adjacency: [
        { name: '동래구', code: '21060' },
        { name: '금정구', code: '21110' },
        { name: '수영구', code: '21140' },
        { name: '기장군', code: '21310' },
      ],
    },
    {
      name: '사하구',
      code: '21100',
      adjacency: [
        { name: '서구', code: '21020' },
        { name: '강서구', code: '21120' },
        { name: '사상구', code: '21150' },
      ],
    },
    {
      name: '금정구',
      code: '21110',
      adjacency: [
        { name: '부산진구', code: '21050' },
        { name: '동래구', code: '21060' },
        { name: '해운대구', code: '21090' },
        { name: '북구', code: '21080' },
        { name: '기장군', code: '21310' },
      ],
    },
    {
      name: '강서구',
      code: '21120',
      adjacency: [
        { name: '북구', code: '21080' },
        { name: '사하구', code: '21100' },
      ],
    },
    {
      name: '연제구',
      code: '21130',
      adjacency: [
        { name: '부산진구', code: '21050' },
        { name: '동래구', code: '21060' },
        { name: '수영구', code: '21140' },
      ],
    },
    {
      name: '수영구',
      code: '21140',
      adjacency: [
        { name: '남구', code: '21070' },
        { name: '해운대구', code: '21090' },
        { name: '연제구', code: '21130' },
      ],
    },
    {
      name: '사상구',
      code: '21150',
      adjacency: [
        { name: '부산진구', code: '21050' },
        { name: '북구', code: '21080' },
        { name: '사하구', code: '21100' },
        { name: '강서구', code: '21120' },
      ],
    },
    {
      name: '기장군',
      code: '21310',
      adjacency: [
        { name: '금정구', code: '21110' },
        { name: '해운대구', code: '21090' },
      ],
    },
  ],
  대구광역시: [
    {
      name: '중구',
      code: '22010',
      adjacency: [
        { name: '남구', code: '22040' },
        { name: '동구', code: '22020' },
        { name: '서구', code: '22030' },
        { name: '북구', code: '22050' },
        { name: '수성구', code: '22060' },
      ],
    },
    {
      name: '동구',
      code: '22020',
      adjacency: [
        { name: '중구', code: '22010' },
        { name: '북구', code: '22050' },
        { name: '수성구', code: '22060' },
        { name: '군위군', code: '22320' },
      ],
    },
    {
      name: '서구',
      code: '22030',
      adjacency: [
        { name: '중구', code: '22010' },
        { name: '북구', code: '22050' },
        { name: '달서구', code: '22070' },
      ],
    },
    {
      name: '남구',
      code: '22040',
      adjacency: [
        { name: '중구', code: '22010' },
        { name: '수성구', code: '22060' },
        { name: '달서구', code: '22070' },
      ],
    },
    {
      name: '북구',
      code: '22050',
      adjacency: [
        { name: '중구', code: '22010' },
        { name: '동구', code: '22020' },
        { name: '서구', code: '22030' },
        { name: '수성구', code: '22060' },
        { name: '달서구', code: '22070' },
        { name: '군위군', code: '22320' },
      ],
    },
    {
      name: '수성구',
      code: '22060',
      adjacency: [
        { name: '중구', code: '22010' },
        { name: '동구', code: '22020' },
        { name: '남구', code: '22040' },
        { name: '북구', code: '22050' },
      ],
    },
    {
      name: '달서구',
      code: '22070',
      adjacency: [
        { name: '서구', code: '22030' },
        { name: '남구', code: '22040' },
        { name: '북구', code: '22050' },
        { name: '달성군', code: '22310' },
      ],
    },
    {
      name: '달성군',
      code: '22310',
      adjacency: [{ name: '달서구', code: '22070' }],
    },
    {
      name: '군위군',
      code: '22320',
      adjacency: [
        { name: '동구', code: '22020' },
        { name: '북구', code: '22050' },
      ],
    },
  ],
  인천광역시: [
    {
      name: '중구',
      code: '23010',
      adjacency: [
        { name: '동구', code: '23020' },
        { name: '미추홀구', code: '23030' },
        { name: '서구', code: '23080' },
        { name: '옹진군', code: '23320' },
        { name: '연수구', code: '23040' },
      ],
    },
    {
      name: '동구',
      code: '23020',
      adjacency: [
        { name: '중구', code: '23010' },
        { name: '미추홀구', code: '23030' },
        { name: '서구', code: '23080' },
      ],
    },
    {
      name: '미추홀구',
      code: '23030',
      adjacency: [
        { name: '중구', code: '23010' },
        { name: '동구', code: '23020' },
        { name: '서구', code: '23080' },
        { name: '남동구', code: '23050' },
        { name: '연수구', code: '23040' },
      ],
    },
    {
      name: '연수구',
      code: '23040',
      adjacency: [
        { name: '중구', code: '23010' },
        { name: '미추홀구', code: '23030' },
        { name: '남동구', code: '23050' },
      ],
    },
    {
      name: '남동구',
      code: '23050',
      adjacency: [
        { name: '미추홀구', code: '23030' },
        { name: '연수구', code: '23040' },
        { name: '부평구', code: '23060' },
        { name: '계양구', code: '23070' },
        { name: '서구', code: '23080' },
      ],
    },
    {
      name: '부평구',
      code: '23060',
      adjacency: [
        { name: '남동구', code: '23050' },
        { name: '계양구', code: '23070' },
        { name: '서구', code: '23080' },
      ],
    },
    {
      name: '계양구',
      code: '23070',
      adjacency: [
        { name: '남동구', code: '23050' },
        { name: '부평구', code: '23060' },
        { name: '서구', code: '23080' },
      ],
    },
    {
      name: '서구',
      code: '23080',
      adjacency: [
        { name: '중구', code: '23010' },
        { name: '동구', code: '23020' },
        { name: '미추홀구', code: '23030' },
        { name: '남동구', code: '23050' },
        { name: '부평구', code: '23060' },
        { name: '계양구', code: '23070' },
        { name: '강화군', code: '23310' },
      ],
    },
    {
      name: '강화군',
      code: '23310',
      adjacency: [
        { name: '서구', code: '23080' },
        { name: '옹진군', code: '23320' },
      ],
    },
    {
      name: '옹진군',
      code: '23320',
      adjacency: [
        { name: '중구', code: '23010' },
        { name: '강화군', code: '23310' },
      ],
    },
  ],
  광주광역시: [
    {
      name: '동구',
      code: '24010',
      adjacency: [
        { name: '서구', code: '24020' },
        { name: '남구', code: '24030' },
        { name: '북구', code: '24040' },
      ],
    },
    {
      name: '서구',
      code: '24020',
      adjacency: [
        { name: '동구', code: '24010' },
        { name: '남구', code: '24030' },
        { name: '북구', code: '24040' },
        { name: '광산구', code: '24050' },
      ],
    },
    {
      name: '남구',
      code: '24030',
      adjacency: [
        { name: '동구', code: '24010' },
        { name: '서구', code: '24020' },
        { name: '광산구', code: '24050' },
      ],
    },
    {
      name: '북구',
      code: '24040',
      adjacency: [
        { name: '동구', code: '24010' },
        { name: '서구', code: '24020' },
        { name: '광산구', code: '24050' },
      ],
    },
    {
      name: '광산구',
      code: '24050',
      adjacency: [
        { name: '서구', code: '24020' },
        { name: '남구', code: '24030' },
        { name: '북구', code: '24040' },
      ],
    },
  ],
  대전광역시: [
    {
      name: '동구',
      code: '25010',
      adjacency: [
        { name: '중구', code: '25020' },
        { name: '대덕구', code: '25050' },
      ],
    },
    {
      name: '중구',
      code: '25020',
      adjacency: [
        { name: '동구', code: '25010' },
        { name: '서구', code: '25030' },
        { name: '유성구', code: '25040' },
        { name: '대덕구', code: '25050' },
      ],
    },
    {
      name: '서구',
      code: '25030',
      adjacency: [
        { name: '중구', code: '25020' },
        { name: '유성구', code: '25040' },
      ],
    },
    {
      name: '유성구',
      code: '25040',
      adjacency: [
        { name: '중구', code: '25020' },
        { name: '서구', code: '25030' },
        { name: '대덕구', code: '25050' },
      ],
    },
    {
      name: '대덕구',
      code: '25050',
      adjacency: [
        { name: '동구', code: '25010' },
        { name: '중구', code: '25020' },
        { name: '유성구', code: '25040' },
      ],
    },
  ],
  울산광역시: [
    {
      name: '중구',
      code: '26010',
      adjacency: [
        { name: '남구', code: '26020' },
        { name: '동구', code: '26030' },
        { name: '북구', code: '26040' },
        { name: '울주군', code: '26310' },
      ],
    },
    {
      name: '남구',
      code: '26020',
      adjacency: [
        { name: '중구', code: '26010' },
        { name: '동구', code: '26030' },
        { name: '북구', code: '26040' },
        { name: '울주군', code: '26310' },
      ],
    },
    {
      name: '동구',
      code: '26030',
      adjacency: [
        { name: '중구', code: '26010' },
        { name: '남구', code: '26020' },
        { name: '북구', code: '26040' },
      ],
    },
    {
      name: '북구',
      code: '26040',
      adjacency: [
        { name: '중구', code: '26010' },
        { name: '남구', code: '26020' },
        { name: '동구', code: '26030' },
        { name: '울주군', code: '26310' },
      ],
    },
    {
      name: '울주군',
      code: '26310',
      adjacency: [
        { name: '중구', code: '26010' },
        { name: '남구', code: '26020' },
        { name: '북구', code: '26040' },
      ],
    },
  ],
  세종특별자치시: [{ name: '세종시', code: '29010', adjacency: [] }],
  경기도: [
    { name: '수원시', code: '31010', adjacency: [] },
    { name: '수원시 장안구', code: '31011', adjacency: [] },
    { name: '수원시 권선구', code: '31012', adjacency: [] },
    { name: '수원시 팔달구', code: '31013', adjacency: [] },
    { name: '수원시 영통구', code: '31014', adjacency: [] },
    { name: '성남시', code: '31020', adjacency: [] },
    { name: '성남시 수정구', code: '31021', adjacency: [] },
    { name: '성남시 중원구', code: '31022', adjacency: [] },
    { name: '성남시 분당구', code: '31023', adjacency: [] },
    { name: '의정부시', code: '31030', adjacency: [] },
    { name: '안양시', code: '31040', adjacency: [] },
    { name: '안양시 만안구', code: '31041', adjacency: [] },
    { name: '안양시 동안구', code: '31042', adjacency: [] },
    { name: '부천시', code: '31050', adjacency: [] },
    { name: '광명시', code: '31060', adjacency: [] },
    { name: '평택시', code: '31070', adjacency: [] },
    { name: '동두천시', code: '31080', adjacency: [] },
    { name: '안산시', code: '31090', adjacency: [] },
    { name: '안산시 상록구', code: '31091', adjacency: [] },
    { name: '안산시 단원구', code: '31092', adjacency: [] },
    { name: '고양시', code: '31100', adjacency: [] },
    { name: '고양시 덕양구', code: '31101', adjacency: [] },
    { name: '고양시 일산동구', code: '31103', adjacency: [] },
    { name: '고양시 일산서구', code: '31104', adjacency: [] },
    { name: '과천시', code: '31110', adjacency: [] },
    { name: '구리시', code: '31120', adjacency: [] },
    { name: '남양주시', code: '31130', adjacency: [] },
    { name: '오산시', code: '31140', adjacency: [] },
    { name: '시흥시', code: '31150', adjacency: [] },
    { name: '군포시', code: '31160', adjacency: [] },
    { name: '의왕시', code: '31170', adjacency: [] },
    { name: '하남시', code: '31180', adjacency: [] },
    { name: '용인시', code: '31190', adjacency: [] },
    { name: '용인시 처인구', code: '31191', adjacency: [] },
    { name: '용인시 기흥구', code: '31192', adjacency: [] },
    { name: '용인시 수지구', code: '31193', adjacency: [] },
    { name: '파주시', code: '31200', adjacency: [] },
    { name: '이천시', code: '31210', adjacency: [] },
    { name: '안성시', code: '31220', adjacency: [] },
    { name: '김포시', code: '31230', adjacency: [] },
    { name: '화성시', code: '31240', adjacency: [] },
    { name: '광주시', code: '31250', adjacency: [] },
    { name: '양주시', code: '31260', adjacency: [] },
    { name: '포천시', code: '31270', adjacency: [] },
    { name: '여주시', code: '31280', adjacency: [] },
    { name: '연천군', code: '31350', adjacency: [] },
    { name: '가평군', code: '31370', adjacency: [] },
    { name: '양평군', code: '31380', adjacency: [] },
  ],
  강원특별자치도: [
    { name: '춘천시', code: '32010', adjacency: [] },
    { name: '원주시', code: '32020', adjacency: [] },
    { name: '강릉시', code: '32030', adjacency: [] },
    { name: '동해시', code: '32040', adjacency: [] },
    { name: '태백시', code: '32050', adjacency: [] },
    { name: '속초시', code: '32060', adjacency: [] },
    { name: '삼척시', code: '32070', adjacency: [] },
    { name: '홍천군', code: '32310', adjacency: [] },
    { name: '횡성군', code: '32320', adjacency: [] },
    { name: '영월군', code: '32330', adjacency: [] },
    { name: '평창군', code: '32340', adjacency: [] },
    { name: '정선군', code: '32350', adjacency: [] },
    { name: '철원군', code: '32360', adjacency: [] },
    { name: '화천군', code: '32370', adjacency: [] },
    { name: '양구군', code: '32380', adjacency: [] },
    { name: '인제군', code: '32390', adjacency: [] },
    { name: '고성군', code: '32400', adjacency: [] },
    { name: '양양군', code: '32410', adjacency: [] },
  ],
  충청북도: [
    { name: '충주시', code: '33020', adjacency: [] },
    { name: '제천시', code: '33030', adjacency: [] },
    { name: '청주시', code: '33040', adjacency: [] },
    { name: '청주시 상당구', code: '33041', adjacency: [] },
    { name: '청주시 서원구', code: '33042', adjacency: [] },
    { name: '청주시 흥덕구', code: '33043', adjacency: [] },
    { name: '청주시 청원구', code: '33044', adjacency: [] },
    { name: '보은군', code: '33320', adjacency: [] },
    { name: '옥천군', code: '33330', adjacency: [] },
    { name: '영동군', code: '33340', adjacency: [] },
    { name: '진천군', code: '33350', adjacency: [] },
    { name: '괴산군', code: '33360', adjacency: [] },
    { name: '음성군', code: '33370', adjacency: [] },
    { name: '단양군', code: '33380', adjacency: [] },
    { name: '증평군', code: '33390', adjacency: [] },
  ],
  충청남도: [
    { name: '천안시', code: '34010', adjacency: [] },
    { name: '천안시 동남구', code: '34011', adjacency: [] },
    { name: '천안시 서북구', code: '34012', adjacency: [] },
    { name: '공주시', code: '34020', adjacency: [] },
    { name: '보령시', code: '34030', adjacency: [] },
    { name: '아산시', code: '34040', adjacency: [] },
    { name: '서산시', code: '34050', adjacency: [] },
    { name: '논산시', code: '34060', adjacency: [] },
    { name: '계룡시', code: '34070', adjacency: [] },
    { name: '당진시', code: '34080', adjacency: [] },
    { name: '금산군', code: '34310', adjacency: [] },
    { name: '부여군', code: '34330', adjacency: [] },
    { name: '서천군', code: '34340', adjacency: [] },
    { name: '청양군', code: '34350', adjacency: [] },
    { name: '홍성군', code: '34360', adjacency: [] },
    { name: '예산군', code: '34370', adjacency: [] },
    { name: '태안군', code: '34380', adjacency: [] },
  ],
  전북특별자치도: [
    { name: '전주시', code: '35010', adjacency: [] },
    { name: '전주시 완산구', code: '35011', adjacency: [] },
    { name: '전주시 덕진구', code: '35012', adjacency: [] },
    { name: '군산시', code: '35020', adjacency: [] },
    { name: '익산시', code: '35030', adjacency: [] },
    { name: '정읍시', code: '35040', adjacency: [] },
    { name: '남원시', code: '35050', adjacency: [] },
    { name: '김제시', code: '35060', adjacency: [] },
    { name: '완주군', code: '35310', adjacency: [] },
    { name: '진안군', code: '35320', adjacency: [] },
    { name: '무주군', code: '35330', adjacency: [] },
    { name: '장수군', code: '35340', adjacency: [] },
    { name: '임실군', code: '35350', adjacency: [] },
    { name: '순창군', code: '35360', adjacency: [] },
    { name: '고창군', code: '35370', adjacency: [] },
    { name: '부안군', code: '35380', adjacency: [] },
  ],
  전라남도: [
    { name: '목포시', code: '36010', adjacency: [] },
    { name: '여수시', code: '36020', adjacency: [] },
    { name: '순천시', code: '36030', adjacency: [] },
    { name: '나주시', code: '36040', adjacency: [] },
    { name: '광양시', code: '36060', adjacency: [] },
    { name: '담양군', code: '36310', adjacency: [] },
    { name: '곡성군', code: '36320', adjacency: [] },
    { name: '구례군', code: '36330', adjacency: [] },
    { name: '고흥군', code: '36350', adjacency: [] },
    { name: '보성군', code: '36360', adjacency: [] },
    { name: '화순군', code: '36370', adjacency: [] },
    { name: '장흥군', code: '36380', adjacency: [] },
    { name: '강진군', code: '36390', adjacency: [] },
    { name: '해남군', code: '36400', adjacency: [] },
    { name: '영암군', code: '36410', adjacency: [] },
    { name: '무안군', code: '36420', adjacency: [] },
    { name: '함평군', code: '36430', adjacency: [] },
    { name: '영광군', code: '36440', adjacency: [] },
    { name: '장성군', code: '36450', adjacency: [] },
    { name: '완도군', code: '36460', adjacency: [] },
    { name: '진도군', code: '36470', adjacency: [] },
    { name: '신안군', code: '36480', adjacency: [] },
  ],
  경상북도: [
    { name: '포항시', code: '37010', adjacency: [] },
    { name: '포항시 남구', code: '37011', adjacency: [] },
    { name: '포항시 북구', code: '37012', adjacency: [] },
    { name: '경주시', code: '37020', adjacency: [] },
    { name: '김천시', code: '37030', adjacency: [] },
    { name: '안동시', code: '37040', adjacency: [] },
    { name: '구미시', code: '37050', adjacency: [] },
    { name: '영주시', code: '37060', adjacency: [] },
    { name: '영천시', code: '37070', adjacency: [] },
    { name: '상주시', code: '37080', adjacency: [] },
    { name: '문경시', code: '37090', adjacency: [] },
    { name: '경산시', code: '37100', adjacency: [] },
    { name: '군위군', code: '37310', adjacency: [] },
    { name: '의성군', code: '37320', adjacency: [] },
    { name: '청송군', code: '37330', adjacency: [] },
    { name: '영양군', code: '37340', adjacency: [] },
    { name: '영덕군', code: '37350', adjacency: [] },
    { name: '청도군', code: '37360', adjacency: [] },
    { name: '고령군', code: '37370', adjacency: [] },
    { name: '성주군', code: '37380', adjacency: [] },
    { name: '칠곡군', code: '37390', adjacency: [] },
    { name: '예천군', code: '37400', adjacency: [] },
    { name: '봉화군', code: '37410', adjacency: [] },
    { name: '울진군', code: '37420', adjacency: [] },
    { name: '울릉군', code: '37430', adjacency: [] },
  ],
  경상남도: [
    { name: '진주시', code: '38030', adjacency: [] },
    { name: '통영시', code: '38050', adjacency: [] },
    { name: '사천시', code: '38060', adjacency: [] },
    { name: '김해시', code: '38070', adjacency: [] },
    { name: '밀양시', code: '38080', adjacency: [] },
    { name: '거제시', code: '38090', adjacency: [] },
    { name: '양산시', code: '38100', adjacency: [] },
    { name: '창원시', code: '38110', adjacency: [] },
    { name: '창원시 의창구', code: '38111', adjacency: [] },
    { name: '창원시 성산구', code: '38112', adjacency: [] },
    { name: '창원시 마산합포구', code: '38113', adjacency: [] },
    { name: '창원시 마산회원구', code: '38114', adjacency: [] },
    { name: '창원시 진해구', code: '38115', adjacency: [] },
    { name: '의령군', code: '38310', adjacency: [] },
    { name: '함안군', code: '38320', adjacency: [] },
    { name: '창녕군', code: '38330', adjacency: [] },
    { name: '고성군', code: '38340', adjacency: [] },
    { name: '남해군', code: '38350', adjacency: [] },
    { name: '하동군', code: '38360', adjacency: [] },
    { name: '산청군', code: '38370', adjacency: [] },
    { name: '함양군', code: '38380', adjacency: [] },
    { name: '거창군', code: '38390', adjacency: [] },
    { name: '합천군', code: '38400', adjacency: [] },
  ],
  제주특별자치도: [
    { name: '제주시', code: '39010', adjacency: [] },
    { name: '서귀포시', code: '39020', adjacency: [] },
  ],
};
