export default function PrivacyPolicy() {
  return (
    <div className="mx-auto w-full max-w-4xl rounded-lg bg-white p-6 font-sans text-gray-800 shadow sm:p-8 md:p-10">
      <h1 className="mb-8 text-center text-3xl font-bold text-gray-900">
        개인정보처리방침
      </h1>

      <section className="mb-8 space-y-4">
        <h2 className="border-b pb-2 text-2xl font-semibold text-gray-800">
          1. 총칙
        </h2>
        <p className="text-base leading-relaxed">
          본 개인정보처리방침은 'Nearby Books'(이하 '서비스')가 사용자의
          개인정보를 어떻게 수집, 이용, 보관하는지에 대한 정보를 제공합니다.
          서비스는 사용자의 개인정보를 소중하게 생각하며, 개인정보보호 관련
          법규를 준수하고 있습니다.
        </p>
      </section>

      <section className="mb-8 space-y-4">
        <h2 className="border-b pb-2 text-2xl font-semibold text-gray-800">
          2. 개인정보 수집 항목 및 이용 목적
        </h2>
        <p className="text-base leading-relaxed">
          서비스는 사용자의 현재 위치 기반으로 주변 도서관 정보를 제공하기 위해
          다음과 같은 개인정보를 수집 및 이용합니다.
        </p>
        <div className="pl-4">
          <p className="font-semibold text-gray-700">수집 항목:</p>
          <p className="ml-4">사용자의 현재 위치 정보 (위도, 경도)</p>
          <p className="mt-2 font-semibold text-gray-700">이용 목적:</p>
          <ul className="ml-8 list-disc space-y-1">
            <li>사용자 주변의 도서관 위치를 지도에 표시</li>
            <li>
              '현 위치에서 검색' 기능을 통해 지도 중심의 주소 정보(시/도,
              시/군/구)를 파악하여 도서관 재검색
            </li>
          </ul>
        </div>
      </section>

      <section className="mb-8 space-y-4">
        <h2 className="border-b pb-2 text-2xl font-semibold text-gray-800">
          3. 개인정보 보유 및 이용기간
        </h2>
        <p className="text-base leading-relaxed">
          서비스는 사용자의 위치 정보를 서버에 저장하지 않으며, 서비스 이용
          시에만 일시적으로 사용합니다. 따라서 서비스 이용이 종료되면 수집된
          위치 정보는 즉시 파기됩니다.
        </p>
      </section>

      <section className="mb-8 space-y-4">
        <h2 className="border-b pb-2 text-2xl font-semibold text-gray-800">
          4. 개인정보 제3자 제공
        </h2>
        <p className="text-base leading-relaxed">
          서비스는 사용자의 개인정보를 제3자에게 제공하지 않습니다.
        </p>
      </section>

      <section className="mb-8 space-y-4">
        <h2 className="border-b pb-2 text-2xl font-semibold text-gray-800">
          5. 개인정보 파기절차 및 방법
        </h2>
        <p className="text-base leading-relaxed">
          서비스는 사용자의 위치 정보를 서버에 저장하지 않으므로 별도의 파기
          절차를 거치지 않습니다. 위치 정보는 서비스 이용 시에만 일시적으로
          사용되며, 서비스 이용 종료 시 즉시 파기됩니다.
        </p>
      </section>

      <section className="mb-8 space-y-4">
        <h2 className="border-b pb-2 text-2xl font-semibold text-gray-800">
          6. 이용자의 권리 및 행사방법
        </h2>
        <p className="text-base leading-relaxed">
          사용자는 언제든지 위치 정보 제공 동의를 거부할 수 있습니다. 동의를
          거부할 경우, 현재 위치 기반의 도서관 검색 기능 이용에 제한이 있을 수
          있으나, 다른 기능(예: 지역 설정 검색)은 정상적으로 이용 가능합니다.
        </p>
      </section>

      <section className="mb-8 space-y-4">
        <h2 className="border-b pb-2 text-2xl font-semibold text-gray-800">
          7. 개인정보 자동 수집 장치의 설치/운영 및 거부에 관한 사항
        </h2>
        <p className="text-base leading-relaxed">
          서비스는 사용자의 위치 정보 외에 쿠키 등 별도의 개인정보 자동 수집
          장치를 사용하지 않습니다.
        </p>
      </section>

      <section className="mb-8 space-y-4">
        <h2 className="border-b pb-2 text-2xl font-semibold text-gray-800">
          8. 개인정보보호 책임자
        </h2>
        <p className="text-base leading-relaxed">
          서비스는 개인정보 처리에 관한 업무를 총괄해서 책임지고, 개인정보
          처리와 관련한 정보주체의 불만처리 및 피해구제 등을 위하여 아래와 같이
          개인정보 보호책임자를 지정하고 있습니다.
        </p>
        <div className="pl-4">
          <p>
            <strong className="font-medium">이메일:</strong>{" "}
            ashesdown0069@gmail.com
          </p>
        </div>
      </section>

      <section className="mb-8 space-y-4">
        <h2 className="border-b pb-2 text-2xl font-semibold text-gray-800">
          9. 개인정보 처리방침 변경
        </h2>
        <p className="text-base leading-relaxed">
          본 개인정보처리방침은 법령 및 방침에 따른 변경내용의 추가, 삭제 및
          정정이 있는 경우에는 변경사항의 시행 7일 전부터 공지사항을 통하여
          고지할 것입니다.
        </p>
      </section>

      <div className="mt-10 border-t pt-4 text-right text-gray-500">
        <p>시행일자: 2025년 9월 26일</p>
        <p>Generated by Gemini</p>
      </div>
    </div>
  );
}
